"""empty message

Revision ID: 415df9028e30
Revises: 
Create Date: 2020-03-19 11:01:05.373051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415df9028e30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guides', sa.Column('act_level', sa.String(), nullable=True))
    op.add_column('guides', sa.Column('address', sa.String(), nullable=True))
    op.add_column('guides', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('guides', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('guides', sa.Column('calender', sa.String(), nullable=True))
    op.add_column('guides', sa.Column('cred', sa.String(), nullable=True))
    op.add_column('guides', sa.Column('cvlink', sa.String(), nullable=True))
    op.add_column('guides', sa.Column('email', sa.String(), nullable=True))
    op.add_column('guides', sa.Column('exp', sa.String(), nullable=True))
    op.add_column('guides', sa.Column('freetime', sa.String(), nullable=True))
    op.add_column('guides', sa.Column('language', sa.String(), nullable=True))
    op.add_column('guides', sa.Column('linkin', sa.String(), nullable=True))
    op.add_column('guides', sa.Column('list_review', sa.String(), nullable=True))
    op.add_column('guides', sa.Column('location', sa.String(), nullable=True))
    op.add_column('guides', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('guides', sa.Column('price_hour', sa.String(), nullable=True))
    op.add_column('guides', sa.Column('rating', sa.String(), nullable=True))
    op.add_column('guides', sa.Column('videolink', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guides', 'videolink')
    op.drop_column('guides', 'rating')
    op.drop_column('guides', 'price_hour')
    op.drop_column('guides', 'phone')
    op.drop_column('guides', 'location')
    op.drop_column('guides', 'list_review')
    op.drop_column('guides', 'linkin')
    op.drop_column('guides', 'language')
    op.drop_column('guides', 'freetime')
    op.drop_column('guides', 'exp')
    op.drop_column('guides', 'email')
    op.drop_column('guides', 'cvlink')
    op.drop_column('guides', 'cred')
    op.drop_column('guides', 'calender')
    op.drop_column('guides', 'bio')
    op.drop_column('guides', 'avatar')
    op.drop_column('guides', 'address')
    op.drop_column('guides', 'act_level')
    # ### end Alembic commands ###
