"""empty message

Revision ID: 8fe99feed7f9
Revises: 415df9028e30
Create Date: 2020-03-19 11:58:22.344145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fe99feed7f9'
down_revision = '415df9028e30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('list_review', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('cred', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('videolink', sa.String(), nullable=True),
    sa.Column('cvlink', sa.String(), nullable=True),
    sa.Column('linkin', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('act_level', sa.String(), nullable=True),
    sa.Column('exp', sa.String(), nullable=True),
    sa.Column('price_hour', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('freetime', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('calender', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guides')
    # ### end Alembic commands ###
